# Generated by Django 3.2.4 on 2021-06-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_rename_matchdetails_match_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match_detail',
            name='id',
        ),
        migrations.AddField(
            model_name='match_detail',
            name='matchId',
            field=models.IntegerField(default=10001, primary_key=True, serialize=False),
        ),
    ]
