# Generated by Django 3.2.4 on 2021-06-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210630_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates_Detail',
            fields=[
                ('dateId', models.AutoField(primary_key=True, serialize=False)),
                ('onDate', models.DateField()),
            ],
        ),
    ]
