# Generated by Django 3.2.4 on 2021-06-30 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_dates_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='series_detail',
            name='dateId',
            field=models.ForeignKey(default=2019, on_delete=django.db.models.deletion.CASCADE, to='mainapp.dates_detail'),
            preserve_default=False,
        ),
    ]
