# Generated by Django 3.2.4 on 2021-06-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210630_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateDataTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changeTime', models.DateTimeField()),
            ],
        ),
    ]
