# Generated by Django 3.2.4 on 2021-07-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_updatedatatime'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_detail',
            name='matchLatitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='match_detail',
            name='matchLongitude',
            field=models.FloatField(default=0),
        ),
    ]
