# Generated by Django 3.2.4 on 2021-07-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_match_detail_matchlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_detail',
            name='matchWeatherTime',
            field=models.CharField(default='future', max_length=50),
        ),
    ]
