# Generated by Django 3.2.4 on 2021-07-03 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_auto_20210703_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match_detail',
            old_name='matchCurrentCloud',
            new_name='matchCloud',
        ),
        migrations.RenameField(
            model_name='match_detail',
            old_name='matchCurrentCondition',
            new_name='matchCondition',
        ),
        migrations.RenameField(
            model_name='match_detail',
            old_name='matchCurrentHumidity',
            new_name='matchHumidity',
        ),
        migrations.RenameField(
            model_name='match_detail',
            old_name='matchCurrentTemp',
            new_name='matchTemp',
        ),
    ]
