# Generated by Django 3.2.4 on 2021-07-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_rename_matchweathertime_match_detail_matchtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_detail',
            name='matchStatus',
            field=models.CharField(default='Scores will appear once the match starts.', max_length=50),
        ),
    ]
