# Generated by Django 3.2.4 on 2021-07-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_match_detail_matchstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_detail',
            name='matchStatus',
            field=models.CharField(default='Scores will appear once the match starts.', max_length=500),
        ),
    ]
