# Generated by Django 3.2.4 on 2021-07-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_alter_match_detail_matchstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_detail',
            name='matchFirstInning',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='match_detail',
            name='matchSecondInning',
            field=models.CharField(default='', max_length=500),
        ),
    ]
