# Generated by Django 3.2.4 on 2021-07-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20210726_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_detail',
            name='matchFirstInning',
            field=models.CharField(default='Not Started', max_length=500),
        ),
        migrations.AlterField(
            model_name='match_detail',
            name='matchSecondInning',
            field=models.CharField(default='Not Started', max_length=500),
        ),
    ]
