# Generated by Django 3.2.4 on 2021-07-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20210726_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_detail',
            name='matchFirstInning',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='match_detail',
            name='matchSecondInning',
            field=models.CharField(default='', max_length=500),
        ),
    ]
